language: cpp
dist: xenial
os:
- linux
compiler:
- clang
- gcc
script:
- cd gatb-core
- mkdir build
- cd build
- make $MAKEFLAGS
- export CPPUNIT_VERBOSE=TRUE && ./bin/gatb-core-cppunit
env:
  global:
    - MAKEFLAGS="-j 4"
