language: cpp
dist: xenial
os:
- linux
compiler:
- clang
- gcc
addons:
  apt:
    sources:
    - george-edison55-precise-backports  # for cmake 3
    packages:
    - cmake
    - cmake-data
script:
- cd gatb-core
- mkdir build
- cd build
- cmake .. && make 
- export CPPUNIT_VERBOSE=TRUE && ./bin/gatb-core-cppunit
env:
  global:
    - MAKEFLAGS="-j 4"
