language: cpp
dist: xenial
os:
- linux
compiler:
- clang
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - george-edison55-precise-backports  # for cmake 3
    packages:
    - libcppunit-dev
    - cmake
    - cmake-data
script:
- cd gatb-core
- mkdir build
- cd build
- cmake .. && make $MAKEFLAGS 
- export CPPUNIT_VERBOSE=TRUE && ./bin/gatb-core-cppunit
env:
  global:
    - MAKEFLAGS="-j 4"

