version: 1
jobs:
  build:
      docker:
        - image: "debian:stretch"
      steps:
        - checkout
        - run:
            name: Installing SUDO
            command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
        - run:
            name: Installing GCC
            command: 'apt-get update && apt-get install -y build-essential wget zlib1g zlib1g-dev'
        - run:
            name: Install CMAKE
            command: |
              wget https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz
              tar -xvzf cmake-3.10.2-Linux-x86_64.tar.gz
              chmod +x ./cmake-3.10.2-Linux-x86_64/bin/ccmake
              chmod +x ./cmake-3.10.2-Linux-x86_64/bin/cmake
              chmod +x ./cmake-3.10.2-Linux-x86_64/bin/cpack
              chmod +x ./cmake-3.10.2-Linux-x86_64/bin/ctest
              DIR=$(pwd)
              ln -s $DIR/cmake-3.10.2-Linux-x86_64/bin/ccmake /usr/bin/ccmake
              ln -s $DIR/cmake-3.10.2-Linux-x86_64/bin/cmake /usr/bin/cmake
              ln -s $DIR/cmake-3.10.2-Linux-x86_64/bin/cpack /usr/bin/cpack
              ln -s $DIR/cmake-3.10.2-Linux-x86_64/bin/ctest /usr/bin/ctest
        - run:
            name: Install CPPUnit
            command: 'apt-get update && sudo apt-get install -y libcppunit-dev'
        - run:
            name: Creating Build Files
            command: 'cd gatb-core && mkdir build && cd build && cmake .. && make -j 4'
        # looks like circleci charges credits so i better not run the cppunit tests..
        #        - run:
        #            name: CPPUnit test
        #            command: 'export CPPUNIT_VERBOSE=TRUE && cd gatb-core/build && ./bin/gatb-core-cppunit'
