version: 1
jobs:
  build:
      docker:
        - image: "debian:stretch"
      steps:
        - checkout
        - run:
            name: Installing SUDO
            command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
        - run:
            name: Installing GCC
            command: 'apt-get update && apt-get install -y gcc g++'
        - run:
            name: Install CMAKE
            command: 'apt-get update && sudo apt-get install -y cmake'
        - run:
            name: Install CPPUnit
            command: 'apt-get update && sudo apt-get install -y libcppunit-dev'
        - run:
            name: Creating Build Files
            command: 'mkdir build && cd build && cmake .. && make -j 4'
        - run:
            name: CPPUnit test
            command: 'export CPPUNIT_VERBOSE=TRUE && ./bin/gatb-core-cppunit'
