# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      build:
          docker:
            - image: "debian:stretch"
          steps:
            - checkout
            - run:
                name: Installing SUDO
                command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
            - run:
                name: Installing GCC
                command: 'apt-get update && apt-get install -y gcc g++'
            - run:
                name: Install CMAKE
                command: 'apt-get update && sudo apt-get install -y cmake'
            - run:
                name: Install CPPUnit
                command: 'apt-get update && sudo apt-get install -y libcppunit-dev'
            - run:
                name: Creating Build Files
                command: 'mkdir build && cd build && cmake .. && make -j 4'
            - run:
                name: CPPUnit test
                command: 'export CPPUNIT_VERBOSE=TRUE && ./bin/gatb-core-cppunit'